rawdataToCleanDataConversionUsingPythonEDA

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
# !pip install --upgrade openpyxl
# incase of any error pls install openpyxl

In [4]:
emp = pd.read_excel(r"E:\FSDS_Reply\EDA\CW\Rawdata.xlsx")

In [5]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [6]:
id(emp) # id means address of emp

2191389376000

In [7]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [8]:
emp.shape

(6, 6)

In [9]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [10]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [11]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [12]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [13]:
emp.isnull() # to find null values

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [14]:
emp.isna() # to find null values

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [15]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [16]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [17]:
emp.dtypes # all attri treated as object by system due to reg-exp

Name        object
Domain      object
Age         object
Location    object
Salary      object
Exp         object
dtype: object

In [18]:
emp.describe() # count of values peresent in attributes (Age = 4 & Location = 4)

        Name         Domain       Age Location  Salary Exp
count      6              6         4        4       6   5
unique     6              6         4        4       6   5
top     Mike  Datascience#$  34 years   Mumbai  5^00#0  2+
freq       1              1         1        1       1   1

In [19]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [20]:
type(emp) # type of object

pandas.core.frame.DataFrame

In [21]:
emp.describe()

        Name         Domain       Age Location  Salary Exp
count      6              6         4        4       6   5
unique     6              6         4        4       6   5
top     Mike  Datascience#$  34 years   Mumbai  5^00#0  2+
freq       1              1         1        1       1   1

In [22]:
emp['Name'] # to view all values in col

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

# data cleaning

In [23]:
emp['Name'] = emp['Name'].str.replace(r'\W','',regex=True)

In [24]:
emp # Name cleaned

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [25]:
emp['Domain'] = emp['Domain'].str.replace(r'\W','',regex=True)

In [26]:
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [27]:
emp['Location'] = emp['Location'].str.replace(r'\W','',regex=True)
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [28]:
emp['Age'] = emp['Age'].str.replace(r'\W','',regex=True) # we have number & text & Sp chars

In [29]:
emp

    Name       Domain      Age   Location   Salary      Exp
0   Mike  Datascience  34years     Mumbai   5^00#0       2+
1  Teddy      Testing     45yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst      NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics      NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67yr        NaN   30000-  5+ year
5    Kim          NLP     55yr      Delhi  6000^$0      10+

In [30]:
emp['Age'] = emp['Age'].str.extract('(\d+)') # keep only numbers

In [31]:
emp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [32]:
emp['Salary'] = emp['Salary'].str.replace(r'\W','',regex=True)

In [33]:
emp

    Name       Domain  Age   Location Salary      Exp
0   Mike  Datascience   34     Mumbai   5000       2+
1  Teddy      Testing   45  Bangalore  10000       <3
2   Umar  Dataanalyst  NaN        NaN  15000   4> yrs
3   Jane    Analytics  NaN   Hyderbad  20000      NaN
4  Uttam   Statistics   67        NaN  30000  5+ year
5    Kim          NLP   55      Delhi  60000      10+

In [34]:
emp['Salary'] = emp['Salary'].str.extract('(\d+)')

In [35]:
emp

    Name       Domain  Age   Location Salary      Exp
0   Mike  Datascience   34     Mumbai   5000       2+
1  Teddy      Testing   45  Bangalore  10000       <3
2   Umar  Dataanalyst  NaN        NaN  15000   4> yrs
3   Jane    Analytics  NaN   Hyderbad  20000      NaN
4  Uttam   Statistics   67        NaN  30000  5+ year
5    Kim          NLP   55      Delhi  60000      10+

In [36]:
emp['Exp']

0         2+
1         <3
2     4> yrs
3        NaN
4    5+ year
5        10+
Name: Exp, dtype: object

In [38]:
emp['Exp'] = emp['Exp'].str.extract('(\d+)') #extract only digit

In [39]:
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

#so far we did the datacleaning on any project this is first setp

emp_cleanData = emp.copy()

In [41]:
emp_cleanData

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [ ]:
emp_cleanData # data stored in memory

In [42]:
emp_cleanData.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

# EDA tech :  missing value Treatment

In [43]:
emp_cleanData['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

# as it is numeric need to apply mean median mode logic to fill missing data

In [45]:
import numpy as np

In [48]:
emp_cleanData['Age'] = emp_cleanData['Age'].fillna(np.mean(pd.to_numeric(emp_cleanData['Age'])))

In [49]:
emp_cleanData['Age'] # applied mean startegy (avg of all numeric values)

0       34
1       45
2    50.25
3    50.25
4       67
5       55
Name: Age, dtype: object

In [50]:
emp_cleanData['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [51]:
emp_cleanData['Location'] = emp_cleanData['Location'].fillna(np.mode(pd.to_numeric(emp_cleanData['Location'])))

AttributeError: module 'numpy' has no attribute 'mode'

In [58]:
emp_cleanData['Location'] = emp_cleanData['Location'].fillna(emp_cleanData['Location'].mode()[0])

In [59]:
emp_cleanData['Location']

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [56]:
emp_cleanData

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  NaN
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [60]:
emp_cleanData['Exp'] = emp_cleanData['Exp'].fillna(np.mean(pd.to_numeric(emp_cleanData['Exp'])))

In [61]:
emp_cleanData

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [62]:
id(emp_cleanData) #this is there inmemory under emp_cleanData var

2191469059472

In [63]:
emp_cleanData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      object
 3   Location  6 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [64]:
emp_cleanData.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [66]:
#all types are object converting int & string (catogerical)
emp_cleanData['Age'] = emp_cleanData['Age'].astype(int)
emp_cleanData['Exp'] = emp_cleanData['Exp'].astype(int)
emp_cleanData['Salary'] = emp_cleanData['Salary'].astype(int)



emp_cleanData['Name'] = emp_cleanData['Name'].astype(int)
emp_cleanData['Domain'] = emp_cleanData['Domain'].astype(int)
emp_cleanData['Location'] = emp_cleanData['Location'].astype(int)

ValueError: invalid literal for int() with base 10: 'Mike'

In [72]:
#all types are object converting int & string (catogerical)
# astype convert the sys defined types(object) to userdefined datatype
emp_cleanData['Age'] = emp_cleanData['Age'].astype(int)
emp_cleanData['Exp'] = emp_cleanData['Exp'].astype(int)
emp_cleanData['Salary'] = emp_cleanData['Salary'].astype(float)



emp_cleanData['Name'] = emp_cleanData['Name'].astype('category')
emp_cleanData['Domain'] = emp_cleanData['Domain'].astype('category')
emp_cleanData['Location'] = emp_cleanData['Location'].astype('category')

In [71]:
emp_cleanData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int64
 3   Location  6 non-null      category
 4   Salary    6 non-null      float64
 5   Exp       6 non-null      int64
dtypes: category(3), float64(1), int64(2)
memory usage: 938.0 bytes

In [75]:
emp_cleanData.to_csv('emp_cleanData.csv')

In [73]:
import os
os.getcwd() #file will stored in this location to share

'C:\\Users\\mani'